name: Validate for HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "integration"

      - name: Upload HACS validation results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: hacs-validation-results
          path: hacs_validation.log
