name: "Validate"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Tägliche Überprüfung um Mitternacht UTC
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  hassfest: # Validierung für Home Assistant Integrationen
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs: # HACS-spezifische Validierung
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          # Entferne diesen Schlüssel, wenn du Logos zur Home Assistant Brands-Repo hinzugefügt hast
          ignore: "brands"
